### PR TITLE
Bug/dockerfile

### PR DESCRIPTION
**Pull request by wisniax**
Devcontainer failing to build

### CODE REVIEW

**Comment by wisniax** [comment]
Hmm, s1 actually could just look at it and accept the changes... its not that big PR 
@bartbart2003 @AlvaroBajceps

**Review by AlvaroBajceps — CHANGES_REQUESTED** [review]
`paho.mqtt.cpp` is not building. 

Checkout to tag v1.3.2 seems to be fixing the issue.

```dockerfile
RUN git checkout v1.3.2
```
added before this line:
https://github.com/wisniax/raptor_ws/blob/84f4afccf5a1d497aefdd5ce00aa12c695a75d57/.devcontainer/Dockerfile#L38

**Comment by wisniax** [comment]
> `paho.mqtt.cpp` is not building.
> 
> Checkout to tag v1.3.2 seems to be fixing the issue.
> 
> ```dockerfile
> RUN git checkout v1.3.2
> ```
> 
> added before this line:
> 
> https://github.com/wisniax/raptor_ws/blob/84f4afccf5a1d497aefdd5ce00aa12c695a75d57/.devcontainer/Dockerfile#L38

Hmm it did work in May tho...
Also u should consider using Suggestion Block ;)

**Comment by AlvaroBajceps** [comment]
Nah, suggestion block can only be applied to changed lines, it says.

**Comment by wisniax** [comment]
Should be fine now

**Review by AlvaroBajceps — APPROVED** [review]
- [x] Dev Container builds (docker image)
- [x] Repo builds inside Dev Container
- [x] Repo seems to be launching inside Dev Container

Me happy

**Pull request merged**
